ARG BASE_IMAGE=sirvingethesecond/ros2-jazzy-base:latest
FROM ${BASE_IMAGE}

# Install desktop packages
ARG ROS_DISTRO=jazzy
RUN apt-get update && apt-get install -y --no-install-recommends \
    ros-${ROS_DISTRO}-desktop \
    && rm -rf /var/lib/apt/lists/*

# Set up environment
ENV ROS_DISTRO=${ROS_DISTRO}